version: "2"

services:
  web-application:
    build:
      context: server
    restart: always
    tty: true
    container_name: downloader
    ports:
    - "5000:5000"
    environment:
      DOWNLOADS_DIR: "/opt/downloads"
    volumes: []
      #- "~/Downloads:/opt/downloads"
      #- "~/Downloads:/opt/db"
