version: "2"

services:
  web:
    build:
      context: web
      args: 
        http_port: 80
    environment:  
      CORS_STRING: "*"
    restart: "no"
    tty: true
    container_name: web
    ports:
    - "80:80"
