version: "2"

services:
  frontend:
    build:
      context: client
    restart: always
    tty: true
    container_name: frontend
    ports:
    - "80:80"

  api-backend:
    build:
      context: go-server
    restart: always
    tty: true
    container_name: api-backend
    ports:
    - "5000:5000"
